device:
  tlc59208f_board_basic_esp8266:
    board: nodemcuv2
    mixins:
    - clock_pin: GPIO5
      data_pin: GPIO4
      id: i2c_1
      kind: i2c_bus
    - address: 16
      id: tlc59208f_1
      kind: tlc59208f_board
