device:
  am2320_sensor_basic_esp8266:
    board: d1_mini_pro
    mixins:
    - clock_pin: GPIO5
      data_pin: GPIO4
      id: i2c_1
      kind: i2c_bus
    - kind: am2320_sensor
      name: test_sensor
