device:
  i2c_bus_multiple_esp32:
    board: nodemcu-32s
    mixins:
    - clock_pin: 13
      data_pin: 16
      id: ic2_1
      kind: i2c_bus
    - clock_pin: 14
      data_pin: 15
      id: i2c_2
      kind: i2c_bus
