device:
  sds011_sensor_basic_esp32:
    board: nodemcu-32s
    mixins:
    - id: uart_1
      kind: uart_bus
      rx_pin: GPIO3
      tx_pin: GPIO1
    - bus: uart_1
      kind: sds011_sensor
      name: test_sensor
