device:
  pcf8575_board_basic_esp8266:
    board: nodemcuv2
    mixins:
    - clock_pin: GPIO5
      data_pin: GPIO4
      id: i2c_1
      kind: i2c_bus
    - address: 33
      id: pcf8575_1
      kind: pcf8575_board
