display:
- busy_pin: GPIO4
  cs_pin: GPIO5
  dc_pin: GPIO22
  full_update_every: 3600
  id: display_output
  lambda: it.print(0, 0, id(opensans), "Hello World!");
  model: 2.90in
  platform: waveshare_epaper
  reset_pin: GPIO21
esphome:
  board: nodemcu-32s
  name: waveshare_epaper_display_basic
  platform: ESP32
font:
- file: ../fonts/OpenSans-Regular.ttf
  id: opensans
  size: 20
logger:
  level: DEBUG
spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23