device:
  uln2003_stepper_advanced:
    board: nodemcuv2
    mixins:
    - acceleration: inf
      deceleration: inf
      dir_pin: D1
      kind: a4988_stepper
      max_speed: 250
      name: test_motor
      step_pin: D0
