display:
- address: '0x3C'
  id: display_output
  model: SSD1306 128x64
  pages:
  - id: page1
    lambda: it.print(0, 0, id(opensans), "Hello World!");
  - id: page2
    lambda: it.print(0, 0, id(opensans), "Good Bye!");
  platform: ssd1306_i2c
esphome:
  board: nodemcu-32s
  name: ssd1306_i2c_display_128x64_esp32
  platform: ESP32
font:
- file: ../fonts/OpenSans-Regular.ttf
  id: opensans
  size: 20
i2c:
- id: i2c_1
  scan: true
  scl: GPIO22
  sda: GPIO21
interval:
- interval: 10s
  then:
  - display.page.show_next: display_output
  - component.update: display_output
logger:
  level: DEBUG