esphome:
  board: nodemcuv2
  includes:
  - ../includes/ezo_orp.h
  libraries:
  - Ezo_I2c_lib
  name: ezo_orp_sensor_basic_esp8266
  platform: ESP8266
i2c:
- id: i2c_1
  scan: true
  scl: GPIO5
  sda: GPIO4
logger:
  esp8266_store_log_strings_in_flash: false
  level: DEBUG
sensor:
- lambda: 'auto ezo_orp_sensor = new EzoOrpSensor(10000, 0x62);

    App.register_component(ezo_orp_sensor);

    return {ezo_orp_sensor};

    '
  platform: custom
  sensors:
  - accuracy_decimals: 2
    id: test_sensor_orp
    name: test_sensor_orp
    unit_of_measurement: mV