api:
  password: api-pass
  services:
  - service: set_angle_test_motor
    then:
    - lambda: 'id(test_motor).write(angle / 90.0);

        ESP_LOGD("api_set_angle_test_motor", "Set angle of servo test_motor");

        '
    variables:
      angle: float
  - service: detach_servo_test_motor
    then:
    - lambda: 'id(test_motor).detach();

        ESP_LOGD("api_detach_servo_test_motor", "Detached servo test_motor");

        '
esphome:
  board: nodemcuv2
  name: gpio_pwm_servo_basic_esp8266
  platform: ESP8266
logger:
  esp8266_store_log_strings_in_flash: false
  level: DEBUG
output:
- frequency: 50Hz
  id: test_motor_output
  pin: D1
  platform: esp8266_pwm
servo:
- id: test_motor
  name: test_motor
  output: test_motor_output
wifi:
  domain: .local
  fast_connect: true
  networks:
  - password: wlan-key
    ssid: wlan-essid