device:
  pca9685_board_basic_esp8266:
    board: nodemcuv2
    mixins:
    - clock_pin: GPIO5
      data_pin: GPIO4
      id: i2c_1
      kind: i2c_bus
    - address: 64
      id: pca9685_1
      kind: pca9685_board
