device:
  dallas_ds18_sensor_multiple_buses:
    board: nodemcuv2
    mixins:
    - id: dallas_1
      kind: dallas_bus
      pin: D1
    - id: dallas_2
      kind: dallas_bus
      pin: D2
    - address: 2017612646464694824
      bus: dallas_1
      kind: dallas_ds18_sensor
      name: test_sensor_1
    - address: 2017612646464694808
      bus: dallas_2
      kind: dallas_ds18_sensor
      name: test_sensor_2
