esphome:
  board: nodemcu-32s
  includes:
  - ../includes/ezo_ph.h
  libraries:
  - Ezo_I2c_lib
  name: ezo_ph_sensor_basic_esp32
  platform: ESP32
i2c:
- id: i2c_1
  scan: true
  scl: GPIO22
  sda: GPIO21
logger:
  level: DEBUG
sensor:
- lambda: 'auto ezo_ph_sensor = new EzoPhSensor(10000, 0x63);

    App.register_component(ezo_ph_sensor);

    return {ezo_ph_sensor};

    '
  platform: custom
  sensors:
  - accuracy_decimals: 2
    id: test_sensor_ph
    name: test_sensor_ph
    unit_of_measurement: ''