device:
  uln2003_stepper_advanced:
    board: nodemcuv2
    mixins:
    - acceleration: inf
      deceleration: inf
      kind: uln2003_stepper
      max_speed: 250 steps/s
      name: test_motor
      pin_a: D0
      pin_b: D1
      pin_c: D2
      pin_d: D3
