esphome:
  board: nodemcu-32s
  name: scd30_sensor_basic_esp32
  platform: ESP32
i2c:
- id: i2c_1
  scan: true
  scl: GPIO22
  sda: GPIO21
logger:
  level: DEBUG
sensor:
- address: '0x61'
  co2:
    accuracy_decimals: 1
    id: test_sensor_co2
    name: test_sensor_co2
  humidity:
    accuracy_decimals: 1
    id: test_sensor_humidity
    name: test_sensor_humidity
  i2c_id: i2c_1
  platform: scd30
  temperature:
    accuracy_decimals: 2
    id: test_sensor_temperature
    name: test_sensor_temperature
  update_interval: 5s