device:
  ezo_ph_sensor_basic_esp32:
    board: nodemcu-32s
    mixins:
    - clock_pin: GPIO22
      data_pin: GPIO21
      id: i2c_1
      kind: i2c_bus
    - address: 99
      bus: i2c_1
      kind: ezo_ph_sensor
      name: test_sensor
      update_interval: 10s
