device:
  pca9685_servo_basic_esp8266:
    board: nodemcuv2
    mixins:
    - clock_pin: D1
      data_pin: D2
      kind: i2c_bus
      name: i2c_1
    - address: 64
      bus: i2c_1
      kind: pca9685_board
      name: pca_1
    - bus: pca_1
      channel: 0
      kind: pca9685_servo
      name: test_motor
    networks:
    - api_password: api-pass
      essid: wlan-essid
      key: wlan-key
