device:
  ezo_orp_sensor_basic_esp8266:
    board: nodemcuv2
    mixins:
    - clock_pin: GPIO5
      data_pin: GPIO4
      id: i2c_1
      kind: i2c_bus
    - address: 98
      bus: i2c_1
      kind: ezo_orp_sensor
      name: test_sensor
      update_interval: 10s
