esphome:
  board: nodemcuv2
  name: pca9685_board_basic_esp8266
  platform: ESP8266
i2c:
- id: i2c_1
  scan: true
  scl: GPIO5
  sda: GPIO4
logger:
  esp8266_store_log_strings_in_flash: false
  level: DEBUG
pca9685:
- address: '0x40'
  frequency: 500
  id: pca9685_1