esphome:
  board: nodemcuv2
  includes:
  - ../includes/ezo_do.h
  libraries:
  - Ezo_I2c_lib
  name: ezo_do_sensor_basic_esp8266
  platform: ESP8266
i2c:
- id: i2c_1
  scan: true
  scl: GPIO5
  sda: GPIO4
logger:
  esp8266_store_log_strings_in_flash: false
  level: DEBUG
sensor:
- lambda: 'auto ezo_do_sensor = new EzoDoSensor(10000, 0x61);

    App.register_component(ezo_do_sensor);

    return {ezo_do_sensor};

    '
  platform: custom
  sensors:
  - accuracy_decimals: 2
    id: test_sensor_dissolved_oxygen
    name: test_sensor_dissolved_oxygen
    unit_of_measurement: mg/L