device:
  amg88xx_camera_basic_esp32:
    board: nodemcu-32s
    mixins:
    - clock_pin: GPIO22
      data_pin: GPIO21
      id: i2c_1
      kind: i2c_bus
    - address: 105
      bus: i2c_1
      kind: amg88xx_camera
      name: test_sensor
      update_interval: 3s
