device:
  pn532_sensor_basic_esp8266:
    board: nodemcuv2
    mixins:
    - clk_pin: D1
      id: spi_1
      kind: spi_bus
      miso_pin: D0
    - bus: spi_1
      cs_pin: D2
      kind: pn532_sensor
      name: test_sensor
      tags:
      - name: tag-01
        uid: 74-10-37-94
      - name: tag-02
        uid: 34-5s7-32-10
