device:
  waveshare_epaper_display_pages:
    board: nodemcu-32s
    mixins:
    - clk_pin: GPIO18
      kind: spi_bus
      mosi_pin: GPIO23
      name: spi_1
    - file: ../fonts/OpenSans-Regular.ttf
      kind: ttf_font
      name: opensans
      size: 20
    - bus: spi_1
      busy_pin: GPIO4
      cs_pin: GPIO5
      cycle_interval: 30s
      dc_pin: GPIO22
      full_update_every: 3600
      kind: waveshare_epaper_display
      model: 2.90in
      name: display_output
      pages:
      - id: page1
        lambda: it.print(0, 0, id(opensans), "Hello World!");
      - id: page2
        lambda: it.print(0, 0, id(opensans), "Good Bye!");
      reset_pin: GPIO21
      rotation: '90'
