device:
  sht3x_sensor_basic_esp8266:
    board: nodemcuv2
    mixins:
    - clock_pin: GPIO5
      data_pin: GPIO4
      id: i2c_1
      kind: i2c_bus
    - bus: i2c_1
      kind: sht3x_sensor
      name: test_sensor
