device:
  tsl2591_sensor_basic_esp8266:
    board: nodemcuv2
    mixins:
    - clock_pin: GPIO5
      data_pin: GPIO4
      id: i2c_1
      kind: i2c_bus
    - bus: i2c_1
      kind: tsl2591_sensor
      name: test_sensor
      update_interval: 5s
